### ISSUE TITLE
[Request]: Contribute to CNIL's guide for developers by adding a section about security

### ISSUE THREAD

**Issue by milstan** [blindnet-io/devrel-management#1]
The French GDPR authority, CNIL, has a guide for developers. It covers a broad range of topics related to making GDPR-compliant software. However it does not cover very well the Article 32 (security of treatment) and what a developer can do to make compliant and secure software.

The idea here is to contribute to the [CNIL's guide, which is open-source](https://github.com/LINCnil/Guide-RGPD-du-developpeur) and add best practice information including (if applicable) a mention of blindnet's open-source tools.

**Comment by noelmace** [comment]
I unfortunately didn't have time for this issue during Q3.

@milstan could you set the priority for this issue in the Communication project, so I can determine when to address it? Thx. Feel free to move it to the Q4 milestone if it seems relevant to you (i.e. wasn't a mandatory goal to meet for Q3).

**Comment by milstan** [comment]
I think this would have been useful back then, as it was a nice opportunity to start making outrreach with the product we had back then. 

Now the product evolved, includes more features and I no longer see this as priority.
