### ISSUE TITLE
rename repositories according to the blindnet devkit brand

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#10]
IMHO, we should:

- invert language and type (e.g. _blindnet js SDK_) to avoid any confusion with the previous informal "blindnet SDK" branding
- replace backend with server for more clarity and to reflect our Open Core approach

Then, we can use, depending on the context (i.e. whatever is clearer):

1.  _blindnet devkit {language} {type}_ (e.g. the blindnet devkit JS SDK)
2.  _blindnet {language} {type}_ (e.g. blindnet JS SDK)

IMHO, repositories' names should keep using (2), while the README titles and repo description should use (1) (e.g. ***blindnet devkit - JavaScript SDK***)

### Docs

Following previous discussions, the docs will soon be renamed and associated with a dedicated brand.

**Comment by filipblnt** [comment]
Apart from the SKDs we also have APIs, so we need to account for that as well. Also, an SDK can be for the client side or the server side of the client's app. That implies the following:

- blindnet devkit {language} {side} {type}  (e.g., `blindnet devkit Java client SDK`,  `blindnet devkit Java server SDK`)
- blindnet devkit {component} API (e.g, `blindnet devkit rights-control API`)

**Comment by filipblnt** [comment]
Now that we are defining the architecture for the devkit, we will have to include different components (e.g., data rights, data capture, etc)

**Comment by m4rk055** [comment]
What do you think about `blindnet devkit {component} {API/SDK} [technology] [additional info]`
`blindnet devkit data-rights API`
`blindnet devkit data-rights SDK Haskell client`

I think the technology should come at the end since it varies the most and the domain is more important.

**Comment by m4rk055** [comment]
Since we have `blindnet.io` as the organisation name, I propose to drop it from repository name.

`blindnet-io/blindnet-sdk-js-client` -> `blindnet-io/sdk-js-client`

**Comment by noelmace** [comment]
-> `blindnet-io/devkit-js-client-sdk` ? :wink:

**Comment by filipblnt** [comment]
To sum up the proposal:

### Repository names

`{component} {API/SDK} [technology] [additional info]`

Examples: `blindnet-io/` +

- `data-rights-api`
- `data-rights-sdk-javascript-client`
- `data-capture-sdk-java-client`

### README titles and repo description

`blindnet devkit {component} {API/SDK} [technology] [additional info]`

Examples: 

- `blindnet devkit data-rights API`
- `blindnet devkit data-rights SDK Javascript client`
- `blindnet devkit data-capture SDK Java client`

**Comment by noelmace** [comment]
@m4rk055 sorry I answered too rapidly

1. totally agree with [removing "blindnet" in the repo name](https://github.com/blindnet-io/devrel-management/issues/10#issuecomment-1153726086) (2)
2. we need clear names saying what the project actually does / is for ([like `data-capture`](https://github.com/blindnet-io/devrel-management/issues/10#issuecomment-1153733089), "devkit" or "SDK" can't be considered sufficient)

So I :100: agree with @filipblnt's https://github.com/blindnet-io/devrel-management/issues/10#issuecomment-1153733089.
I'd just add that the "component" part should be defined with a clear "purpose" in mind.

**Comment by filipblnt** [comment]
All repos that will be public soon have their names changed according to https://github.com/blindnet-io/devrel-management/issues/10#issuecomment-1153733089 .
