### ISSUE TITLE
✨ blindnet logo stickers

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#13]
Some of our investors want us to provide them with blindnet logo laptop stickers (ideally in two colours - one for dark and one for light MacBooks or worse - other laptops).

@milstan  will then also use the opportunity to extend an offer to our other investors, to stick blindnet logos to their laptops :slightly_smiling_face: 

@milstan think we can and we [MUST](https://datatracker.ietf.org/doc/html/rfc2119) ASAP fulfil this request as our investors will promote us heavily in the upcoming weeks.

**Comment by Vuk-BN** [comment]
As an additional ancillary expense, needless to say, we want to minimize the budget impact. I am looking at their pricing options for different sizes. If we opt for 100 4x4 stickers, I see the pricing is $120. Do we think that's enough?

**Comment by milstan** [comment]
more than enough IMHO, for now

**Comment by timnicblind** [comment]
From @milstan first request we need two colour versions, one for black computers and one for white computers. We can't order 100 splitting half and half but we need to take two separate orders. 

Do we take 50 of each or 100 of each in two separate orders?

**Comment by Vuk-BN** [comment]
I'd say 50 in two batches for now, if we really think we need two color options. 

IMHO, I personally wouldn't optimize for laptop colors for now. We can opt for an off-black type of a sticker (grey-ish), so it stands out regrades.

**Comment by timnicblind** [comment]
Ok, so if for @milstan and @noelmace is good we can proceed with only a gray version of the logo.

**Comment by timnicblind** [comment]
@noelmace if you also agree with making a sticker with blindnet logo in gray, could you please provide me a png version of it that could well fit to make the stickers?

**Comment by noelmace** [comment]
Here is a version in gray, but if you want to choose only one color, I'd go with **black**. Gray seems weird, and won't stand out. Most laptop computers are gray or white, not black.

![blindnet-gray](https://user-images.githubusercontent.com/7578400/171185297-ed246f33-df7f-45cb-801a-0fc6230e3a77.png)
![blindnet-light](https://user-images.githubusercontent.com/7578400/171185299-b2d95abb-442e-43fc-8d4c-1035b1557894.png)

**Comment by noelmace** [comment]
If you really want to make sure the logo stands out, we'd need to add a white border to the black version, but I'm not competent enough in image editing to do that.

**Comment by timnicblind** [comment]
I also prefer the black version

**Comment by Vuk-BN** [comment]
+1 for the black version

**Comment by noelmace** [comment]
> Most laptop computers are gray or white, not black.

Addendum: thinkpads are "black", but still kind of grey-ish I guess, so maybe it will still be OK with black stickers, we'll see  :shrug: 

(thx @m4rk055 :laughing:)

![image](https://user-images.githubusercontent.com/7578400/171284609-db66cdc6-7c4b-4fd2-8c28-5bea73398745.png)
