### ISSUE TITLE
Create a simple and unique entry-point for blindnet devkit on Github

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#3]
## What?

Offer a unique entry point on Github to get started and follow the evolution of the blindnet-sdk.

## Why?

Right now, the blindnet-sdk is scattered across different repositories based on specific language versions (js, node, backend, java, etc.).

We need:

- developers to easily get started with the SDK, and get the whole picture
- developers to easily track releases (a common release number should be used to track compatibility)
- us to easily point to a repository

## How?

Several options:

1. merge everything into a single monorepository
2. use git subtrees (:-1:)
3. use git submodules (:-1:)
4. just use [blindnet-docs](https://github.com/blindnet-io/blindnet-docs), and see what we need to change
5. create a new introduction project

**Comment by filipblnt** [comment]
@noelmace Is blindnet-docs in (4) `docs.blindnet.io` or something else?

**Comment by noelmace** [comment]
@filipblnt Yes, it's the associated repository, I made a typo in the link URL

**Comment by filipblnt** [comment]
I'd go with (4) for now, and then (5) at some point.

**Comment by noelmace** [comment]
I agree with @filipblnt as discussed during our last "tech talks".

We'll therefore need to update this project's README accordingly and make the repo public ASAP.
