### ISSUE TITLE
Malt Academy

### ISSUE THREAD

**Issue by nweldev** [blindnet-io/devrel-management#37]
## What

Online conference of my own choice.

We discussed:
- blindnet-io/talks#1
- OR une présentation du concept "Progressive Web Apps" sous l'angle de la gestion des droits et de la privacy (privacy by design / progressive enhancement) (see blindnet-io/___issue-transfer-buffer#22)

## When

2022-09-07 between 1 and 2 pm CET

**Comment by noelmace** [comment]
No news from the Malt Academy team since we planned this.
This will need to be rescheduled with them as the initial due date passed without me receiving information from them.
This could allow me to propose a new talk, closer to our current scope.
