### ISSUE TITLE
[Talk] 🧑‍🎨 The subtle art of frugality

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#43]
> By @ptibulle and @noelmace

## Title

> **Note**
>
> This talk hasn't been translated into English yet.

- **:fr: (fr)**: 🧑‍🎨 L'art délicat de la frugalité

### :fr: (fr)

Eco-conception, Privacy by Design, Web Performance, Pédagogie, Bienveillance... et même le Sketchnoting: vous avez forcément croisé au moins un de ces sujets en conférence récemment.

Et si nous vous disons que tous, oui, absolument tous, découlent d'une même logique ?!

Venez voir se dessiner en direct le combat épique de deux copains contre la distraction et l'abondance !

### :gb: (en)

> :construction: TBD

### :fr: (fr)

> :construction: Draft

> Nouveau talk dessiné en live par Pierre, pour mieux aider à comprendre les histoires de Noël. Cette fois, on part sur quelque chose d'essentiellement technique et scientifique, en nous basant sur des actualités et découvertes récentes.

Nous démarrerons par une rapide introduction aux concepts de minimalisme dans l'art et le design, en soulignant son omniprésence dans notre environnement contemporain, afin de donner un public un ancrage concret, et de souligner les avantages et limitations qu'ils connaissent déjà sans les avoir nécessairement formulés.

Puis Pierre présentera rapidement le sketchnoting et la facilitation graphique en général, pour rappeler pourquoi faire simple est ici indispensable. Il illustrera directement en live tout le reste du talk. À commencer par une suite d'exemples contre-exemples, en "tentant" d'illustrer les concepts de pédagogie et communication présentés par Noël via des phrases et idées tanto simples, tanto inutilement complexes.

Ensuite, nous présenterons comment l'attention au détail et les choix (ainsi que l'envie de toujours en faire trop) se font dans notre cerveaux, en faisant un petit écart par le machine learning, afin d'aider tout le monde à mieux identifier les bonnes et mauvaises habitudes dans ce domaine, et trouver des solutions simples plus rapidement.

Enfin, nous ferons la connexion entre les sujets techniques (performance et privacy-by-design) et écologiques (empreinte carbonne, co-conception et low-tech) pour aboutir à la vie sociale quotidienne (psychologie et sociologie), et ancrer cette idée de frugalité via un exposé simple, mais concret, et applicable à un grand nombre de domaines de manière uniforme.

### :gb: (en)

> :construction: TBD

## Presentations and Recordings

> :hourglass_flowing_sand: Selection in progress...

**Comment by noelmace** [comment]
Bonne idée @ptibulle.

J'ai quand même envie de mettre encore plus en avant le côté "atypique" du talk (le dessin).

Du coup je suis parti sur:
1. Venez **voir** et écouter
2. (même si c'est un peu plus môche), déplacer le "avec un support visuel dessiné en live" au début

Dis moi ce que tu en penses. Dès que c'est bon, j'attaque les bullet points histoire de faire l'elevator pitch.

**Comment by ptibulle** [comment]
Pourquoi pas :
Venez assister au combat épique de deux copains contre la distraction et l'abondance avec un support visuel dessiné en live.
#octogone 🥊 
(les parenthèses c'est moche et oui c'est méta)

**Comment by ptibulle** [comment]
Autre idée : 
Venez voir se dessiner en live le support visuel en écoutant ce combat épique de deux copains contre la distraction et l'abondance !

**Comment by noelmace** [comment]
"Venez voir se dessiner en direct le combat épique de deux copains contre la distraction et l'abondance !" :question:

**Comment by ptibulle** [comment]
C'est validé !

**Comment by noelmace** [comment]
Merci @ptibulle. Je vais faire de mon mieux pour avancer l'elevator pitch d'ici dimanche histoire d'envoyer à Devfest Nantes.

**Comment by noelmace** [comment]
Too late for Devfest Nantes :sweat: 
![image](https://user-images.githubusercontent.com/7578400/174502083-ebc576f2-d26c-46a3-ae75-bc730e81a24e.png)

**Comment by noelmace** [comment]
Abstract enregistré en l'état sur le CFP du [ForumPHP](https://afup.org/event/forumphp2022/cfp/4042).
@ptibulle doit accepter l'invitation avant ce soir pour être comptabilisé comme co-speaker.

**Comment by noelmace** [comment]
Based on the feedback we received, I believe this talk idea isn't good/clear enough to be selected or even to justify spending time on a "more catchy" title and resume.

A "**history of privacy**" would be a way better alternative, as initially discussed.

It would take me an extensive amount of time to research and document everything (especially as it isn't only related to tech) to meet the level of the previous talk. This is why we initially abandoned this idea.

However, @milstan has a lot of theoretical material he assembled under notion-of-privacy, and we even have data to share from the user-study we already conducted, so I believe this could greatly help me here (aiming for a first presentation around January).

@ptibulle let's discuss this on the train to Rotterdam :smiley:
