### ISSUE TITLE
Write Doc: How Privacy Compiler Works

### ISSUE THREAD

**Issue by milstan** [blindnet-io/devrel-management#52]
Transform the [Resolving Requests part of the Expected Behavior document](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/expected-behavior.md#resolving-requests) into an easy-to-read Tutorial.

- Give a high-level, short description on how PC works (Takes PRIV Events, produces a state)
- For each type of PRIV Event, in short say what will happen with the state
- Examples of timelines, and responses for some edge case requests to illustrate it.

@noelmace please let me know where (and in which format) this document should be made. I can start making it, and @blindnet-io/engineering can contribute as they develop.

**Comment by milstan** [comment]
Making-of files for the How Privacy Computation Engine works animation

![PCEexplained](https://user-images.githubusercontent.com/317424/179513295-78a33322-555b-420c-a134-d0db549fd048.gif)
[PCEexplained.pptx](https://github.com/blindnet-io/devrel-management/files/9131918/PCEexplained.pptx)

**Comment by noelmace** [comment]
@milstan _where_: blindnet.dev (see https://github.com/blindnet-io/blindnet.dev/issues/26), _which format_: markdown

**Comment by milstan** [comment]
Thanks. You mean like create a separate file for it in [here](https://github.com/blindnet-io/blindnet.dev/tree/main/docs/how_it_works)?

**Comment by noelmace** [comment]
Yeah for now this would be perfect.
Then, as I'll address #26 (creating new sections require some development, as we only have one for now), I'll move this document to the right section and update it if needed.
