### ISSUE TITLE
Use a consistant name for the default branch in all repositories

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#6]
## What?

Rename `master` to `main` everywhere needed.

## Why?

Using different branch names between projects creates confusion when switching from one project to another, and `main` [is now the by-default standard on GitHub](https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name).

> Personal example: I use the ZSH command history/suggestion for commands like `grbi main` all the time, and need to often ask myself "OK, I'm in project A, is it `main` or `master`".

## How?

Check all repositories in [blindnet-io](https://github.com/blindnet-io) one by one, and [use GitHub](https://github.com/github/renaming#renaming-existing-branches) to rename the branch if needed.

**Comment by noelmace** [comment]
blindnet-docs and product-management were still using a master branch, so I fixed it.

@filipblnt why did you close this issue, and are you sure there isn't any other repo with a master branch?

**Comment by TheKinrar** [comment]
All the "active" code repos (backends, frontends) have switched to main yesterday, but you're right, there's still some older repos with master branches

**Comment by noelmace** [comment]
"Old repos that won't be open / further maintained" should be clearly indicated as such using the "archive" Github feature before we close this issue then, IMHO.

What do you mean by "test respos"?

**Comment by noelmace** [comment]
Thx for the clarification. I agree.
