### ISSUE TITLE
📌 create a first simple tutorial for the DevKit

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#66]
## What?

Write a first simple temporary tutorial explaining how to get started with the DevKit (v0.3 / 0.4, see https://github.com/blindnet-io/product-management/issues/721#issuecomment-1193139007) as a whole.

## Why?

Give a first temporary entry point before we can write more in-depth and independent tutorials for each component as planned in https://github.com/blindnet-io/blindnet.dev/issues/26.

**Comment by milstan** [comment]
This is also needed for DPO Consulting and the meeting with them. So please consider this to done rather by mid-augurst than mid-september.

**Comment by noelmace** [comment]
First version has been published on blindnet.dev [v2.0.0-beta.1](https://github.com/blindnet-io/blindnet.dev/releases/tag/v2.0.0-beta.1) (see https://github.com/blindnet-io/blindnet.dev/pull/34).

I'm therefore considering this issue done, but will open a new one for the second version of the tutorial I am currently writing.
