### ISSUE TITLE
Fix outdated URL: blindnet.dev/docs/quickstart -> tutorial

### ISSUE THREAD

**Issue by tibastral** [blindnet-io/devrel-management#88]
In a lot of repositories, you have a link to the quick start guide pointing to https://blindnet.dev/docs/quickstart, and it should point to https://blindnet.dev/docs/tutorial. Could you make a 302 ? Thank you

**Comment by noelmace** [comment]
Thanks for raising this issue. I will make a 302 + fix the URL when possible and necessary.

**Comment by m4rk055** [comment]
Done. I made it 301 (permanently moved) for SEO.

**Comment by noelmace** [comment]
Thx for the quick fix @m4rk055 :+1: 
The link has also been updated in most README files (seehttps://github.com/blindnet-io/devrel-management/issues/9#issuecomment-1254928633).
I'll review the whole organization for outdated URLs asap (see https://github.com/blindnet-io/devrel-management/issues/90).
